root: true
extends:
  - remcohaszing
rules:
  '@typescript-eslint/no-invalid-void-type': off
overrides:
  - files:
      - '*.md/*.js'
    rules:
      import/no-extraneous-dependencies: off
  - files:
      - '**/*.test.ts'
    rules:
      jsdoc/require-jsdoc: off
      import/no-extraneous-dependencies: off
